"""
Recommendation model — personalised content suggestions for a user.

Recommendations are generated by the recommendation engine (future
phase) and stored here for fast retrieval and personalisation.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import Enum, Float, ForeignKey, String, Text, text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import AppBaseMixin
from app.models.enums import RecommendationType

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.knowledge_node import KnowledgeNode


class Recommendation(AppBaseMixin, Base):
    """A personalised recommendation for a user.

    Generated by the recommendation engine (Phase 6+), each record
    links a user to a knowledge node with a recommendation type,
    score, and optional explanation.
    """

    __tablename__ = 'recommendations'

    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey('users.id', ondelete='CASCADE'),
        nullable=False, index=True,
        comment='Target user ID',
    )
    node_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey('knowledge_nodes.id', ondelete='CASCADE'),
        nullable=False, index=True,
        comment='Recommended knowledge node ID',
    )
    recommendation_type: Mapped[RecommendationType] = mapped_column(
        Enum(RecommendationType, name="recommendation_type_enum", native_enum=True, create_type=False),
        nullable=False, index=True,
        comment='Category of the recommendation',
    )
    score: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True,
        comment='Relevance score (higher = more relevant)',
    )
    reason: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
        comment='Human-readable explanation of why this is recommended',
    )
    extra_metadata: Mapped[dict] = mapped_column(
        'metadata', JSONB, default=dict, server_default=text("'{}'::jsonb"),
        nullable=False,
        comment='Engine metadata (e.g. signals used, model version)',
    )
    is_dismissed: Mapped[bool] = mapped_column(
        default=False, server_default=text('false'),
        nullable=False,
        comment='Whether the user dismissed this recommendation',
    )

    # ── Relationships ──────────────────────────────────────────────

    user: Mapped['User'] = relationship(
        'User', back_populates='recommendations',
    )
    node: Mapped['KnowledgeNode'] = relationship(
        'KnowledgeNode',
    )

    def __repr__(self) -> str:
        return (
            f'<Recommendation user={self.user_id!r} '
            f'node={self.node_id!r} type={self.recommendation_type.value}>'
        )
