"""Recommendation DTOs — personalised content suggestions.

These schemas represent recommendations generated by the recommendation
engine (future phase). They are distinct from KnowledgeRecommendation
(which is knowledge-node-scoped) and CareerRecommendation (which is
career-scoped) — this module provides the generic recommendation
contract used by the recommendation listing endpoints.
"""

from app.schemas.recommendation.recommendation import (
    RecommendationSummary,
    RecommendationDetail,
    RecommendationDismiss,
    RecommendationList,
    RecommendationTypeCount,
)

__all__ = [
    'RecommendationSummary',
    'RecommendationDetail',
    'RecommendationDismiss',
    'RecommendationList',
    'RecommendationTypeCount',
]
