"""Recommendation DTOs — personalised content suggestions.

These schemas represent recommendations generated by the recommendation
engine (future phase). They provide a generic recommendation contract
used by the recommendation listing endpoints, separate from the
knowledge-node-scoped and career-scoped recommendation DTOs.

Note:
    ``KnowledgeRecommendation`` (in ``app.schemas.knowledge.recommendation``)
    is the knowledge-node-specific variant returned from node detail pages.
    ``CareerRecommendation`` (in ``app.schemas.career.recommendation``) is
    the career-specific variant. This module provides the generic
    recommendation list/feed contract.

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from datetime import datetime
    from uuid import UUID

    from app.models.enums import RecommendationType


class RecommendationSummary(BaseModel):
    """Compact recommendation for list views and dashboard feeds."""

    id: UUID = Field(description='Unique recommendation identifier')
    node_id: UUID = Field(description='Recommended knowledge node ID')
    node_slug: str = Field(description='Recommended node slug')
    node_title: str = Field(description='Recommended node title')
    recommendation_type: RecommendationType = Field(description='Category of the recommendation')
    score: float | None = Field(default=None, ge=0.0, le=1.0, description='Relevance score')
    reason: str | None = Field(default=None, description='Human-readable explanation')
    is_dismissed: bool = Field(default=False, description='Whether the user dismissed this')
    created_at: datetime = Field(description='When the recommendation was generated')


class RecommendationDetail(BaseModel):
    """Full recommendation detail with all metadata."""

    id: UUID = Field(description='Unique recommendation identifier')
    user_id: UUID = Field(description='Target user ID')
    node_id: UUID = Field(description='Recommended knowledge node ID')
    node_slug: str = Field(description='Recommended node slug')
    node_title: str = Field(description='Recommended node title')
    recommendation_type: RecommendationType = Field(description='Category of the recommendation')
    score: float | None = Field(default=None, ge=0.0, le=1.0, description='Relevance score')
    reason: str | None = Field(default=None, description='Human-readable explanation')
    metadata: dict = Field(
        default_factory=dict,
        description='Engine metadata (signals, model version)',
    )
    is_dismissed: bool = Field(default=False, description='Whether the user dismissed this')
    created_at: datetime = Field(description='When the recommendation was generated')
    updated_at: datetime = Field(description='When the recommendation was last updated')


class RecommendationDismiss(BaseModel):
    """Request contract for dismissing a recommendation."""

    is_dismissed: bool = Field(
        default=True,
        description='Set to false to un-dismiss a recommendation',
    )


class RecommendationTypeCount(BaseModel):
    """Number of recommendations grouped by type."""

    recommendation_type: RecommendationType = Field(description='The recommendation type')
    count: int = Field(ge=0, description='Number of recommendations of this type')


class RecommendationList(BaseModel):
    """Paginated list of recommendations with type breakdown."""

    items: list[RecommendationSummary] = Field(description='Recommendations for this page')
    total: int = Field(ge=0, description='Total recommendations')
    by_type: list[RecommendationTypeCount] = Field(
        default_factory=list,
        description='Recommendation counts by type for filtering',
    )
