"""Semantic Search Service — vector similarity search across knowledge nodes.

Provides:
- Cosine similarity computation
- Semantic nearest neighbors
- Configurable similarity threshold
- Top-k retrieval

Works with embeddings generated by the EmbeddingService.
"""

from __future__ import annotations

import math
from typing import TYPE_CHECKING

from structlog.stdlib import get_logger

if TYPE_CHECKING:
    from uuid import UUID

    from app.repositories import UnitOfWork

logger = get_logger(__name__)


class SemanticSearchService:
    """Vector-based semantic search over knowledge nodes.

    Finds nodes whose embeddings are closest to a query embedding
    using cosine similarity.

    Future: Replace in-memory search with pgvector or a vector DB
    for production scalability to 100k+ nodes.
    """

    def __init__(self, uow: UnitOfWork) -> None:
        self._uow = uow

    # ── Public API ─────────────────────────────────────────────────

    async def search(
        self,
        query_embedding: list[float],
        limit: int = 20,
        threshold: float = 0.0,
        exclude_node_ids: list[UUID] | None = None,
    ) -> list[dict]:
        """Search for semantically similar nodes.

        Args:
            query_embedding: The query vector to compare against.
            limit: Maximum results to return.
            threshold: Minimum similarity score (0.0 to 1.0).
            exclude_node_ids: Optional node IDs to exclude.

        Returns:
            List of dicts with ``node``, ``similarity``, ``rank``.

        """
        exclude_set = set(exclude_node_ids or [])

        nodes = await self._uow.knowledge_nodes.find_published()

        scored: list[tuple[float, dict]] = []
        for node in nodes:
            if node.id in exclude_set:
                continue

            metadata = node.extra_metadata or {}
            node_embedding = metadata.get('embedding')
            if not node_embedding:
                continue

            similarity = self._cosine_similarity(query_embedding, node_embedding)
            if similarity < threshold:
                continue

            scored.append(
                (
                    similarity,
                    {
                        'node': _node_to_dict(node),
                        'similarity': round(similarity, 4),
                    },
                ),
            )

        # Sort by similarity descending
        scored.sort(key=lambda x: x[0], reverse=True)

        # Assign ranks
        results = []
        for rank, (_, item) in enumerate(scored[:limit], 1):
            item['rank'] = rank
            results.append(item)

        return results

    async def find_similar_to_node(
        self,
        node_id: UUID,
        embedding: list[float] | None = None,
        limit: int = 10,
        threshold: float = 0.3,
    ) -> list[dict]:
        """Find semantically similar nodes to a given node.

        Args:
            node_id: The source node ID.
            embedding: Pre-computed embedding (fetched if not provided).
            limit: Maximum results.
            threshold: Minimum similarity score.

        Returns:
            List of similar node dicts sorted by similarity.

        """
        if embedding is None:
            node = await self._uow.knowledge_nodes.get_by_id(node_id)
            if not node:
                return []
            metadata = node.extra_metadata or {}
            embedding = metadata.get('embedding')
            if not embedding:
                return []

        return await self.search(
            query_embedding=embedding,
            limit=limit + 1,  # +1 to exclude source after scoring
            threshold=threshold,
            exclude_node_ids=[node_id],
        )

    # ── Cosine Similarity ──────────────────────────────────────────

    def _cosine_similarity(self, vec_a: list[float], vec_b: list[float]) -> float:
        """Compute cosine similarity between two vectors.

        Returns a value between 0 and 1 (higher = more similar).
        """
        if not vec_a or not vec_b:
            return 0.0

        dot_product = sum(a * b for a, b in zip(vec_a, vec_b, strict=False))
        norm_a = math.sqrt(sum(a * a for a in vec_a))
        norm_b = math.sqrt(sum(b * b for b in vec_b))

        if norm_a == 0 or norm_b == 0:
            return 0.0

        return dot_product / (norm_a * norm_b)

    async def compute_similarity_matrix(self, node_ids: list[UUID]) -> list[dict]:
        """Compute a pairwise similarity matrix for a set of nodes.

        Returns a list of ``{node_a, node_b, similarity}`` entries
        for all pairs above a default threshold.

        Time: O(N^2 * D) where N = node count, D = embedding dimensions.
        """
        embeddings: dict[UUID, list[float]] = {}
        for nid in node_ids:
            node = await self._uow.knowledge_nodes.get_by_id(nid)
            if node:
                metadata = node.extra_metadata or {}
                emb = metadata.get('embedding')
                if emb:
                    embeddings[nid] = emb

        pairs = []
        ids = list(embeddings.keys())
        for i in range(len(ids)):
            for j in range(i + 1, len(ids)):
                sim = self._cosine_similarity(embeddings[ids[i]], embeddings[ids[j]])
                if sim > 0.3:
                    pairs.append(
                        {
                            'node_a': str(ids[i]),
                            'node_b': str(ids[j]),
                            'similarity': round(sim, 4),
                        },
                    )

        pairs.sort(key=lambda x: float(x['similarity']), reverse=True)  # type: ignore[arg-type]
        return pairs


def _node_to_dict(node) -> dict:
    return {
        'id': str(node.id),
        'slug': node.slug,
        'title': node.title,
        'description': node.description,
        'node_type': node.node_type.value if hasattr(node.node_type, 'value') else node.node_type,
        'difficulty': node.difficulty.value
        if hasattr(node.difficulty, 'value')
        else node.difficulty,
        'estimated_minutes': node.estimated_minutes,
        'icon': node.icon,
        'color': node.color,
        'view_count': node.view_count,
    }
