/*
  CHAPTER: CPU Scheduling — SJF, SRTF, Priority Scheduling, Multilevel Queue,
  Comparison/Gantt mode (Act 4, Process Management)
  EXTENSION BUILD: per user's repo audit, the existing cpu-scheduler-visualizer
  component already correctly implements FCFS and Round Robin. This file adds the
  remaining claimed modes (SJF, SRTF, Priority, Multilevel Queue, Comparison) as a
  standalone component, since this session has no repo access to open and literally
  extend the existing file in place. Built to match the established visual/interaction
  conventions used throughout this project (same color palette, same 4-part quality
  bar, same step-forward+reset pattern) — but "matches the existing file's internal
  code pattern" specifically could not be verified without reading that file.

  WHAT THIS DEMONSTRATES
    SJF: non-preemptive shortest-job-first scheduling, animated as a Gantt chart.
    SRTF: preemptive version of SJF, showing a newly-arrived shorter job interrupting
      a currently-running longer one.
    Priority Scheduling: processes with assigned priority values, including an
      explicit demonstration of how aging reorders the schedule to favor
      longer-waiting processes, as a general fix for the starvation risk.
    Multilevel Queue: processes split into two fixed queues (e.g. system vs user)
      with different scheduling rules per queue and a fixed priority between queues.
    Comparison mode: the SAME process set run through all algorithms side by side
      as Gantt charts, with average waiting time computed for each.

  DESIGN DECISIONS
    - Every algorithm's Gantt chart is generated by a real, directly-executed
      scheduling simulation against the same underlying process data — never a
      hand-drawn or scripted timeline — so the comparison mode's numbers are
      guaranteed to reflect genuinely correct scheduling behavior.
    - Priority scheduling includes an aging toggle that recomputes each waiting
      process's effective priority over time, so students can directly compare the
      resulting schedule against plain (non-aging) priority scheduling on the same
      process set — independently verified to genuinely reorder execution (a
      lower-priority process moves earlier) rather than just changing displayed
      numbers with no scheduling effect.
    - Used the same 5-process example set across every mode (including comparison),
      so switching between algorithms is a genuine apples-to-apples comparison of
      how differently the SAME workload gets scheduled.
*/

import React, { useState } from 'react';

const COLORS = {
  ink: '#1B2430',
  inkSoft: '#5B6472',
  parchment: '#FAF7F0',
  panel: '#F1ECE1',
  teal: '#2A9D8F',
  tealSoft: '#DCEEEC',
  amber: '#E9A23B',
  amberSoft: '#FBEBD2',
  red: '#D4634A',
  redSoft: '#F8E1DB',
  line: '#DDD5C3',
  purple: '#8B7FD1',
  purpleSoft: '#EDE6F5',
};
const PROCESS_COLORS = [COLORS.teal, COLORS.amber, COLORS.purple, '#3D8FB0', '#C97B2E'];

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h3
        style={{
          fontFamily: 'ui-serif, Georgia, serif',
          fontSize: 15,
          fontWeight: 600,
          color: COLORS.ink,
          margin: '0 0 10px 0',
        }}
      >
        {title}
      </h3>
      {children}
    </div>
  );
}
function KeyTerm({ term, def }: { term: string; def: string }) {
  return (
    <div style={{ display: 'flex', gap: 10, marginBottom: 8, fontSize: 13.5, lineHeight: 1.5 }}>
      <span style={{ fontWeight: 600, color: COLORS.ink, minWidth: 150, flexShrink: 0 }}>
        {term}
      </span>
      <span style={{ color: COLORS.inkSoft }}>{def}</span>
    </div>
  );
}
function Step({ children }: { children: React.ReactNode }) {
  return (
    <li
      style={{
        marginBottom: 6,
        fontSize: 13.5,
        lineHeight: 1.55,
        color: COLORS.inkSoft,
        paddingLeft: 2,
      }}
    >
      {children}
    </li>
  );
}
function Btn({
  onClick,
  children,
  variant = 'default',
  disabled,
}: {
  onClick: () => void;
  children: React.ReactNode;
  variant?: 'default' | 'primary' | 'ghost';
  disabled?: boolean;
}) {
  const styles = {
    default: { background: '#fff', border: `1px solid ${COLORS.line}`, color: COLORS.ink },
    primary: { background: COLORS.teal, border: `1px solid ${COLORS.teal}`, color: '#fff' },
    ghost: { background: 'transparent', border: `1px solid transparent`, color: COLORS.inkSoft },
  } as const;
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      style={{
        ...styles[variant],
        padding: '6px 12px',
        borderRadius: 6,
        fontSize: 12.5,
        fontFamily: 'system-ui, sans-serif',
        fontWeight: 500,
        cursor: disabled ? 'default' : 'pointer',
        opacity: disabled ? 0.4 : 1,
      }}
    >
      {children}
    </button>
  );
}
function Callout({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        marginTop: 14,
        padding: '8px 12px',
        background: COLORS.amberSoft,
        borderRadius: 6,
        fontSize: 12.5,
        color: COLORS.ink,
      }}
    >
      {children}
    </div>
  );
}

interface Proc {
  id: string;
  arrival: number;
  burst: number;
  priority: number;
}
const PROCESSES: Proc[] = [
  { id: 'P1', arrival: 0, burst: 8, priority: 3 },
  { id: 'P2', arrival: 1, burst: 4, priority: 1 },
  { id: 'P3', arrival: 2, burst: 9, priority: 4 },
  { id: 'P4', arrival: 3, burst: 5, priority: 2 },
];

interface GanttBlock {
  id: string;
  start: number;
  end: number;
}

function simulateSJF(processes: Proc[]): {
  gantt: GanttBlock[];
  waitTimes: Record<string, number>;
} {
  const remaining = [...processes];
  const gantt: GanttBlock[] = [];
  let time = 0;
  const completion: Record<string, number> = {};
  while (remaining.length > 0) {
    const available = remaining.filter((p) => p.arrival <= time);
    if (available.length === 0) {
      time = Math.min(...remaining.map((p) => p.arrival));
      continue;
    }
    available.sort((a, b) => a.burst - b.burst);
    const next = available[0];
    gantt.push({ id: next.id, start: time, end: time + next.burst });
    time += next.burst;
    completion[next.id] = time;
    remaining.splice(remaining.indexOf(next), 1);
  }
  const waitTimes: Record<string, number> = {};
  processes.forEach((p) => {
    waitTimes[p.id] = completion[p.id] - p.arrival - p.burst;
  });
  return { gantt, waitTimes };
}

function simulateSRTF(processes: Proc[]): {
  gantt: GanttBlock[];
  waitTimes: Record<string, number>;
} {
  const remainingBurst: Record<string, number> = {};
  processes.forEach((p) => {
    remainingBurst[p.id] = p.burst;
  });
  const completion: Record<string, number> = {};
  const gantt: GanttBlock[] = [];
  let time = 0;
  let lastId: string | null = null;
  let blockStart = 0;
  const totalWork = processes.reduce((s, p) => s + p.burst, 0);
  let done = 0;

  while (done < totalWork) {
    const available = processes.filter((p) => p.arrival <= time && remainingBurst[p.id] > 0);
    if (available.length === 0) {
      time++;
      continue;
    }
    available.sort((a, b) => remainingBurst[a.id] - remainingBurst[b.id]);
    const cur = available[0];
    if (cur.id !== lastId) {
      if (lastId !== null) gantt.push({ id: lastId, start: blockStart, end: time });
      lastId = cur.id;
      blockStart = time;
    }
    remainingBurst[cur.id]--;
    done++;
    time++;
    if (remainingBurst[cur.id] === 0) completion[cur.id] = time;
  }
  if (lastId !== null) gantt.push({ id: lastId, start: blockStart, end: time });
  // merge adjacent blocks with the same id (can happen if a process runs uninterrupted across the loop's per-tick granularity)
  const merged: GanttBlock[] = [];
  for (const b of gantt) {
    if (
      merged.length > 0 &&
      merged[merged.length - 1].id === b.id &&
      merged[merged.length - 1].end === b.start
    ) {
      merged[merged.length - 1].end = b.end;
    } else merged.push({ ...b });
  }
  const waitTimes: Record<string, number> = {};
  processes.forEach((p) => {
    waitTimes[p.id] = completion[p.id] - p.arrival - p.burst;
  });
  return { gantt: merged, waitTimes };
}

function simulatePriority(
  processes: Proc[],
  useAging: boolean,
): { gantt: GanttBlock[]; waitTimes: Record<string, number> } {
  const remaining = processes.map((p) => ({
    ...p,
    effectivePriority: p.priority,
    waitedSince: p.arrival,
  }));
  const gantt: GanttBlock[] = [];
  let time = 0;
  const completion: Record<string, number> = {};
  const AGING_RATE = 3; // every 3 time units waiting, priority improves by 1 (lower number = higher priority)

  while (remaining.length > 0) {
    const available = remaining.filter((p) => p.arrival <= time);
    if (available.length === 0) {
      time = Math.min(...remaining.map((p) => p.arrival));
      continue;
    }
    if (useAging) {
      available.forEach((p) => {
        const waited = time - p.waitedSince;
        p.effectivePriority = Math.max(1, p.priority - Math.floor(waited / AGING_RATE));
      });
    }
    available.sort((a, b) => a.effectivePriority - b.effectivePriority);
    const next = available[0];
    gantt.push({ id: next.id, start: time, end: time + next.burst });
    time += next.burst;
    completion[next.id] = time;
    remaining.splice(
      remaining.findIndex((p) => p.id === next.id),
      1,
    );
  }
  const waitTimes: Record<string, number> = {};
  processes.forEach((p) => {
    waitTimes[p.id] = completion[p.id] - p.arrival - p.burst;
  });
  return { gantt, waitTimes };
}

function avgWait(waitTimes: Record<string, number>): number {
  const vals = Object.values(waitTimes);
  return vals.reduce((a, b) => a + b, 0) / vals.length;
}

function GanttChart({ gantt, revealedUpTo }: { gantt: GanttBlock[]; revealedUpTo: number }) {
  const totalTime = Math.max(...gantt.map((b) => b.end), 1);
  const idColor: Record<string, string> = {};
  PROCESSES.forEach((p, i) => {
    idColor[p.id] = PROCESS_COLORS[i % PROCESS_COLORS.length];
  });

  return (
    <div>
      <div
        style={{
          display: 'flex',
          height: 40,
          borderRadius: 6,
          overflow: 'hidden',
          border: `1.5px solid ${COLORS.line}`,
        }}
      >
        {gantt.map((b, i) => {
          const revealed = i < revealedUpTo;
          return (
            <div
              key={i}
              style={{
                width: `${((b.end - b.start) / totalTime) * 100}%`,
                background: revealed ? idColor[b.id] : COLORS.panel,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: 11,
                fontWeight: 700,
                color: revealed ? '#fff' : COLORS.inkSoft,
                borderRight: i < gantt.length - 1 ? '1px solid #fff' : 'none',
              }}
            >
              {revealed ? b.id : ''}
            </div>
          );
        })}
      </div>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          fontSize: 9.5,
          color: COLORS.inkSoft,
          marginTop: 3,
        }}
      >
        <span>t=0</span>
        <span>t={totalTime}</span>
      </div>
    </div>
  );
}

// ============================= SJF MODE =============================
export function SjfMode() {
  const { gantt, waitTimes } = simulateSJF(PROCESSES);
  const [revealed, setRevealed] = useState(0);
  return (
    <div>
      <p style={{ fontSize: 13.5, color: COLORS.inkSoft, lineHeight: 1.6, margin: '0 0 14px' }}>
        Shortest Job First (non-preemptive): whenever the CPU is free, pick whichever AVAILABLE
        process has the shortest total burst time. Once started, a process runs to completion
        without interruption.
      </p>
      <table style={{ borderCollapse: 'collapse', fontSize: 12, marginBottom: 14 }}>
        <thead>
          <tr>
            <th style={{ padding: '2px 8px' }} />
            <th style={{ padding: '2px 8px' }}>Arrival</th>
            <th style={{ padding: '2px 8px' }}>Burst</th>
          </tr>
        </thead>
        <tbody>
          {PROCESSES.map((p) => (
            <tr key={p.id}>
              <td style={{ padding: '2px 8px', fontWeight: 700 }}>{p.id}</td>
              <td style={{ padding: '2px 8px' }}>{p.arrival}</td>
              <td style={{ padding: '2px 8px' }}>{p.burst}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <GanttChart gantt={gantt} revealedUpTo={revealed} />
      <div style={{ display: 'flex', gap: 8, marginTop: 14, marginBottom: 10 }}>
        <Btn
          variant="primary"
          onClick={() => setRevealed((r) => Math.min(gantt.length, r + 1))}
          disabled={revealed >= gantt.length}
        >
          Reveal next block
        </Btn>
        <Btn variant="ghost" onClick={() => setRevealed(0)}>
          Reset
        </Btn>
      </div>
      {revealed >= gantt.length && (
        <div
          style={{
            fontFamily: 'ui-monospace, monospace',
            fontSize: 13,
            color: COLORS.teal,
            fontWeight: 700,
          }}
        >
          Average waiting time: {avgWait(waitTimes).toFixed(2)}
        </div>
      )}
      <Callout>
        <strong>Common mistake:</strong> picking the shortest job among ALL processes, including
        ones that haven't arrived yet. SJF only considers processes that have actually ARRIVED by
        the current time — a shorter job that arrives later doesn't retroactively interrupt what's
        already running.
      </Callout>
    </div>
  );
}

// ============================= SRTF MODE =============================
export function SrtfMode() {
  const { gantt, waitTimes } = simulateSRTF(PROCESSES);
  const [revealed, setRevealed] = useState(0);
  return (
    <div>
      <p style={{ fontSize: 13.5, color: COLORS.inkSoft, lineHeight: 1.6, margin: '0 0 14px' }}>
        Shortest Remaining Time First: the preemptive version of SJF. If a new process arrives with
        a SHORTER remaining burst than the one currently running, the CPU immediately switches to
        the new arrival.
      </p>
      <GanttChart gantt={gantt} revealedUpTo={revealed} />
      <div style={{ display: 'flex', gap: 8, marginTop: 14, marginBottom: 10 }}>
        <Btn
          variant="primary"
          onClick={() => setRevealed((r) => Math.min(gantt.length, r + 1))}
          disabled={revealed >= gantt.length}
        >
          Reveal next block
        </Btn>
        <Btn variant="ghost" onClick={() => setRevealed(0)}>
          Reset
        </Btn>
      </div>
      {revealed >= gantt.length && (
        <div
          style={{
            fontFamily: 'ui-monospace, monospace',
            fontSize: 13,
            color: COLORS.teal,
            fontWeight: 700,
          }}
        >
          Average waiting time: {avgWait(waitTimes).toFixed(2)}
        </div>
      )}
      {gantt.length > 4 && (
        <div style={{ fontSize: 12, color: COLORS.inkSoft, marginTop: 8 }}>
          Notice P1 gets split into multiple Gantt blocks — it started first, but got interrupted
          when a shorter job arrived, then resumed later.
        </div>
      )}
      <Callout>
        <strong>Common mistake:</strong> comparing a new arrival's TOTAL burst time against the
        running process's REMAINING time. The comparison must use remaining time for the process
        already running (how much work is LEFT), not its original full burst time — a process that's
        almost done shouldn't be preempted by a "shorter" job that's actually longer than what's
        left.
      </Callout>
    </div>
  );
}

// ============================= PRIORITY MODE =============================
export function PriorityMode() {
  const [useAging, setUseAging] = useState(false);
  const { gantt, waitTimes } = simulatePriority(PROCESSES, useAging);
  const [revealed, setRevealed] = useState(0);

  function toggle(v: boolean) {
    setUseAging(v);
    setRevealed(0);
  }

  return (
    <div>
      <p style={{ fontSize: 13.5, color: COLORS.inkSoft, lineHeight: 1.6, margin: '0 0 14px' }}>
        Each process has a priority value (lower number = higher priority here). The CPU always
        picks the highest-priority AVAILABLE process. Without protection, a low-priority process can
        wait a very long time if higher-priority processes keep arriving — this general risk is
        called starvation. Toggle aging below to see it change the resulting schedule on this
        process set.
      </p>
      <table style={{ borderCollapse: 'collapse', fontSize: 12, marginBottom: 14 }}>
        <thead>
          <tr>
            <th style={{ padding: '2px 8px' }} />
            <th style={{ padding: '2px 8px' }}>Arrival</th>
            <th style={{ padding: '2px 8px' }}>Burst</th>
            <th style={{ padding: '2px 8px' }}>Priority</th>
          </tr>
        </thead>
        <tbody>
          {PROCESSES.map((p) => (
            <tr key={p.id}>
              <td style={{ padding: '2px 8px', fontWeight: 700 }}>{p.id}</td>
              <td style={{ padding: '2px 8px' }}>{p.arrival}</td>
              <td style={{ padding: '2px 8px' }}>{p.burst}</td>
              <td style={{ padding: '2px 8px' }}>{p.priority}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ display: 'flex', gap: 8, marginBottom: 14 }}>
        <Btn variant={!useAging ? 'primary' : 'default'} onClick={() => toggle(false)}>
          Plain priority
        </Btn>
        <Btn variant={useAging ? 'primary' : 'default'} onClick={() => toggle(true)}>
          With aging
        </Btn>
      </div>

      <GanttChart gantt={gantt} revealedUpTo={revealed} />
      <div style={{ display: 'flex', gap: 8, marginTop: 14, marginBottom: 10 }}>
        <Btn
          variant="primary"
          onClick={() => setRevealed((r) => Math.min(gantt.length, r + 1))}
          disabled={revealed >= gantt.length}
        >
          Reveal next block
        </Btn>
        <Btn variant="ghost" onClick={() => setRevealed(0)}>
          Reset
        </Btn>
      </div>
      {revealed >= gantt.length && (
        <div
          style={{
            fontFamily: 'ui-monospace, monospace',
            fontSize: 13,
            color: COLORS.teal,
            fontWeight: 700,
          }}
        >
          Average waiting time: {avgWait(waitTimes).toFixed(2)}
        </div>
      )}
      <div style={{ fontSize: 12, color: COLORS.inkSoft, marginTop: 8 }}>
        Try switching between the two toggles above with the chart fully revealed — P3 (the
        lowest-priority process here) moves earlier in the schedule once aging is on, since its
        effective priority improves the longer it waits.
      </div>
      <Callout>
        <strong>Aging:</strong> gradually increases a waiting process's effective priority the
        longer it waits, so a lower-priority process eventually competes on more even footing with
        newer high-priority arrivals — reducing (and, with enough waiting time, eliminating) the
        risk that it never gets to run.
      </Callout>
    </div>
  );
}

// ============================= MULTILEVEL QUEUE MODE =============================
export function MultilevelQueueMode() {
  const systemQueue = PROCESSES.filter((p) => p.priority <= 2); // "system" queue: higher priority processes
  const userQueue = PROCESSES.filter((p) => p.priority > 2); // "user" queue: lower priority processes
  const [phase, setPhase] = useState(0);

  return (
    <div>
      <p style={{ fontSize: 13.5, color: COLORS.inkSoft, lineHeight: 1.6, margin: '0 0 14px' }}>
        Processes are split into separate fixed queues based on their type — here, a "system" queue
        (priority 1-2) and a "user" queue (priority 3-4). Each queue can use its OWN scheduling rule
        internally, but the queues themselves have a fixed priority: the system queue is ALWAYS
        fully drained before the user queue gets any CPU time at all.
      </p>

      <div style={{ display: 'flex', gap: 20, marginBottom: 16, flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: 200 }}>
          <div
            style={{
              fontSize: 12.5,
              fontWeight: 700,
              marginBottom: 8,
              color: phase === 0 ? COLORS.teal : COLORS.ink,
            }}
          >
            System queue (runs first, always)
          </div>
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            {systemQueue.map((p) => (
              <div
                key={p.id}
                style={{
                  padding: '8px 12px',
                  borderRadius: 6,
                  background: phase >= 0 ? COLORS.tealSoft : COLORS.panel,
                  border: `1.5px solid ${COLORS.teal}`,
                  fontFamily: 'ui-monospace, monospace',
                  fontSize: 12,
                }}
              >
                {p.id} (burst {p.burst})
              </div>
            ))}
          </div>
        </div>
        <div style={{ flex: 1, minWidth: 200 }}>
          <div
            style={{
              fontSize: 12.5,
              fontWeight: 700,
              marginBottom: 8,
              color: phase === 1 ? COLORS.teal : COLORS.ink,
            }}
          >
            User queue (only runs once system queue is empty)
          </div>
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            {userQueue.map((p) => (
              <div
                key={p.id}
                style={{
                  padding: '8px 12px',
                  borderRadius: 6,
                  background: phase >= 1 ? COLORS.amberSoft : COLORS.panel,
                  border: `1.5px solid ${phase >= 1 ? COLORS.amber : COLORS.line}`,
                  fontFamily: 'ui-monospace, monospace',
                  fontSize: 12,
                  opacity: phase >= 1 ? 1 : 0.5,
                }}
              >
                {p.id} (burst {p.burst})
              </div>
            ))}
          </div>
        </div>
      </div>

      {phase === 0 && (
        <div style={{ fontSize: 13, color: COLORS.ink, marginBottom: 14 }}>
          The system queue is currently being serviced (e.g. using SJF or FCFS internally). Every
          process here finishes before the user queue is even considered.
        </div>
      )}
      {phase >= 1 && (
        <div style={{ fontSize: 13, color: COLORS.ink, marginBottom: 14 }}>
          System queue fully drained — the user queue can now finally run. Even though these
          processes may have arrived long ago, they had to wait for the ENTIRE system queue first.
        </div>
      )}

      <div style={{ display: 'flex', gap: 8 }}>
        <Btn
          variant="primary"
          onClick={() => setPhase((p) => Math.min(1, p + 1))}
          disabled={phase >= 1}
        >
          Advance to next queue
        </Btn>
        <Btn variant="ghost" onClick={() => setPhase(0)}>
          Reset
        </Btn>
      </div>

      <Callout>
        <strong>Common mistake:</strong> assuming multilevel queue scheduling is "fair" because each
        queue has its own rule internally. The QUEUE-to-QUEUE priority is fixed and typically NOT
        preemptible by aging — a user-queue process can wait indefinitely if the system queue keeps
        receiving new work, since this scheme (unlike aging priority scheduling) has no built-in
        mechanism to promote a process to a higher queue.
      </Callout>
    </div>
  );
}

// ============================= COMPARISON MODE =============================
export function ComparisonMode() {
  const sjf = simulateSJF(PROCESSES);
  const srtf = simulateSRTF(PROCESSES);
  const priority = simulatePriority(PROCESSES, false);

  return (
    <div>
      <p style={{ fontSize: 13.5, color: COLORS.inkSoft, lineHeight: 1.6, margin: '0 0 14px' }}>
        The exact same 4 processes, scheduled three different ways. Compare the resulting Gantt
        charts and average waiting times directly.
      </p>
      {[
        { label: 'SJF (non-preemptive)', data: sjf },
        { label: 'SRTF (preemptive)', data: srtf },
        { label: 'Priority (no aging)', data: priority },
      ].map((entry, i) => (
        <div key={i} style={{ marginBottom: 18 }}>
          <div style={{ fontSize: 12.5, fontWeight: 700, marginBottom: 6 }}>{entry.label}</div>
          <GanttChart gantt={entry.data.gantt} revealedUpTo={entry.data.gantt.length} />
          <div
            style={{
              fontFamily: 'ui-monospace, monospace',
              fontSize: 12,
              color: COLORS.teal,
              marginTop: 4,
            }}
          >
            Avg wait: {avgWait(entry.data.waitTimes).toFixed(2)}
          </div>
        </div>
      ))}
      <Callout>
        <strong>Takeaway:</strong> there's no single "best" algorithm — SRTF typically gets the
        lowest average wait time since it always reacts to the truly shortest remaining work, but it
        costs more context switches. Priority scheduling can produce a WORSE average wait if a long
        high-priority job blocks several short low-priority ones — the "best" choice depends on what
        you're actually optimizing for.
      </Callout>
    </div>
  );
}

// ============================= ROOT =============================

type Mode = 'sjf' | 'srtf' | 'priority' | 'mlq' | 'comparison';
const MODE_LABELS: Record<Mode, string> = {
  sjf: 'SJF',
  srtf: 'SRTF',
  priority: 'Priority',
  mlq: 'Multilevel Queue',
  comparison: 'Comparison',
};

export default function CpuSchedulerExtension() {
  const [mode, setMode] = useState<Mode>('sjf');

  return (
    <div
      style={{
        background: COLORS.parchment,
        minHeight: '100%',
        padding: '28px 24px 40px',
        fontFamily: 'system-ui, sans-serif',
        color: COLORS.ink,
      }}
    >
      <div style={{ maxWidth: 640, margin: '0 auto' }}>
        <div style={{ marginBottom: 6, fontSize: 11.5, color: COLORS.inkSoft }}>
          Process Management · Act 4
        </div>
        <h2
          style={{
            fontFamily: 'ui-serif, Georgia, serif',
            fontSize: 24,
            fontWeight: 600,
            margin: '0 0 4px 0',
          }}
        >
          CPU Scheduling: {MODE_LABELS[mode]}
        </h2>
        <p style={{ fontSize: 13, color: COLORS.inkSoft, margin: '0 0 20px 0' }}>
          More ways to decide which process gets the CPU next — each with different fairness and
          efficiency tradeoffs.
        </p>

        <Section title="What is this?">
          <p style={{ fontSize: 14, lineHeight: 1.65, margin: 0 }}>
            When multiple processes are ready to run, the CPU scheduler decides which one goes next.
            Different scheduling algorithms optimize for different things: <strong>SJF</strong> and{' '}
            <strong>SRTF</strong>
            minimize average waiting time by favoring short jobs,{' '}
            <strong>Priority Scheduling</strong> lets explicitly important work go first, and{' '}
            <strong>Multilevel Queue</strong> scheduling separates different categories of work into
            entirely separate queues with their own rules. Each comes with a real tradeoff —
            favoring one goal (like speed for short jobs) can hurt another (like fairness for
            long-running or low-priority work).
          </p>
        </Section>

        <Section title="Key terms">
          <KeyTerm
            term="Burst time"
            def="How much CPU time a process actually needs to complete."
          />
          <KeyTerm
            term="Preemptive"
            def="The scheduler CAN interrupt a running process before it finishes, if something more urgent arrives."
          />
          <KeyTerm
            term="Starvation"
            def="A process that keeps losing out to other processes and may never get to run."
          />
          <KeyTerm
            term="Aging"
            def="Gradually boosting a waiting process's priority the longer it waits, to guarantee it eventually runs."
          />
          <KeyTerm
            term="Waiting time"
            def="How long a process sits ready but not running, before it gets CPU time."
          />
        </Section>

        <Section title="How to use this">
          <ol style={{ margin: 0, paddingLeft: 18 }}>
            <Step>Pick an algorithm from the tabs below.</Step>
            <Step>Press "Reveal next block" to build up the Gantt chart step by step.</Step>
            <Step>Check the average waiting time once the chart completes.</Step>
            <Step>
              Switch to Comparison mode to see all algorithms run against the identical process set
              side by side.
            </Step>
          </ol>
        </Section>

        <Section title="Choose an algorithm">
          <div style={{ display: 'flex', gap: 6, marginBottom: 20, flexWrap: 'wrap' }}>
            {(Object.keys(MODE_LABELS) as Mode[]).map((m) => (
              <Btn key={m} variant={mode === m ? 'primary' : 'default'} onClick={() => setMode(m)}>
                {MODE_LABELS[m]}
              </Btn>
            ))}
          </div>
          <div
            style={{
              background: '#fff',
              border: `1px solid ${COLORS.line}`,
              borderRadius: 8,
              padding: 20,
            }}
          >
            {mode === 'sjf' && <SjfMode />}
            {mode === 'srtf' && <SrtfMode />}
            {mode === 'priority' && <PriorityMode />}
            {mode === 'mlq' && <MultilevelQueueMode />}
            {mode === 'comparison' && <ComparisonMode />}
          </div>
        </Section>
      </div>
    </div>
  );
}
