/**
 * Component: LrParserSim
 * Serves: act7-d5 "LR Parsing" chapter
 *
 * What it demonstrates:
 *   Bottom-up shift-reduce parsing with an explicit state/symbol stack, animating
 *   shift and reduce actions guided by a real SLR(1) ACTION/GOTO table, building the
 *   parse bottom-up from the input tokens up to the start symbol.
 *
 * Design decisions:
 *   - Grammar (augmented: S'→E; E→E+T|T; T→T*F|F; F→(E)|id) is the standard textbook
 *     example specifically because operator precedence (* binds tighter than +)
 *     falls naturally out of the shift/reduce decisions at each state, without the
 *     grammar needing any extra precedence declarations — a nice payoff for seeing
 *     the table-driven mechanism work.
 *   - The ACTION/GOTO table shown was generated by a real SLR(1) construction
 *     (canonical LR(0) item sets + FOLLOW-based reduce actions), verified against an
 *     independent trace before shipping — not hand-guessed — so every shift and
 *     reduce decision in the walkthrough is actually justified by the table, not
 *     scripted to look right.
 *   - The driver that walks the table is a real, general shift-reduce algorithm
 *     (shift on 's', reduce and pop |body| symbols on 'r', accept on 'acc'), so it
 *     would behave correctly on any input over this grammar, not just the one
 *     example string.
 *   - ASSUMPTION: Tailwind + lucide-react available in host repo.
 */
import { AlertTriangle } from 'lucide-react';
import { useState, type ReactNode } from 'react';

const GRAMMAR: [string, string[]][] = [
  ["S'", ['E']],
  ['E', ['E', '+', 'T']],
  ['E', ['T']],
  ['T', ['T', '*', 'F']],
  ['T', ['F']],
  ['F', ['(', 'E', ')']],
  ['F', ['id']],
];

// Verified SLR(1) ACTION table (sN = shift to state N, rP = reduce by production P, acc = accept)
const ACTION: Record<number, Record<string, string>> = {
  0: { '(': 's4', id: 's5' },
  1: { $: 'acc', '+': 's6' },
  2: { $: 'r2', '+': 'r2', ')': 'r2', '*': 's7' },
  3: { $: 'r4', '+': 'r4', '*': 'r4', ')': 'r4' },
  4: { '(': 's4', id: 's5' },
  5: { $: 'r6', '+': 'r6', '*': 'r6', ')': 'r6' },
  6: { '(': 's4', id: 's5' },
  7: { '(': 's4', id: 's5' },
  8: { '+': 's6', ')': 's11' },
  9: { $: 'r1', '+': 'r1', ')': 'r1', '*': 's7' },
  10: { $: 'r3', '+': 'r3', '*': 'r3', ')': 'r3' },
  11: { $: 'r5', '+': 'r5', '*': 'r5', ')': 'r5' },
};
const GOTO: Record<number, Record<string, number>> = {
  0: { E: 1, T: 2, F: 3 },
  4: { E: 8, T: 2, F: 3 },
  6: { T: 9, F: 3 },
  7: { F: 10 },
};

interface TraceStep {
  state: number;
  symStack: string;
  lookahead: string;
  action: string;
}

function parse(tokens: string[]): TraceStep[] {
  const input = [...tokens, '$'];
  let ip = 0;
  const stateStack = [0];
  const symStack: string[] = [];
  const trace: TraceStep[] = [];
  let guard = 0;
  while (guard++ < 100) {
    const s = stateStack[stateStack.length - 1];
    const a = input[ip];
    const act = ACTION[s]?.[a];
    if (!act) {
      trace.push({
        state: s,
        symStack: symStack.join(' '),
        lookahead: a,
        action: 'ERROR: no action',
      });
      break;
    }
    if (act === 'acc') {
      trace.push({ state: s, symStack: symStack.join(' '), lookahead: a, action: 'ACCEPT' });
      break;
    }
    if (act[0] === 's') {
      const target = Number(act.slice(1));
      trace.push({
        state: s,
        symStack: symStack.join(' '),
        lookahead: a,
        action: `shift "${a}", go to state ${target}`,
      });
      symStack.push(a);
      stateStack.push(target);
      ip++;
    } else {
      const pi = Number(act.slice(1));
      const [head, body] = GRAMMAR[pi];
      trace.push({
        state: s,
        symStack: symStack.join(' '),
        lookahead: a,
        action: `reduce by ${head} → ${body.join(' ')}`,
      });
      for (let k = 0; k < body.length; k++) {
        symStack.pop();
        stateStack.pop();
      }
      symStack.push(head);
      const s2 = stateStack[stateStack.length - 1];
      const g = GOTO[s2]?.[head];
      if (g === undefined) {
        trace.push({
          state: s2,
          symStack: symStack.join(' '),
          lookahead: a,
          action: 'ERROR: no goto',
        });
        break;
      }
      stateStack.push(g);
    }
  }
  return trace;
}

const INPUT_TOKENS = ['id', '+', 'id', '*', 'id'];
const TRACE = parse(INPUT_TOKENS);

export default function LrParserSim() {
  const [step, setStep] = useState(0);
  const next = () => setStep((s) => Math.min(TRACE.length - 1, s + 1));
  const reset = () => setStep(0);
  const current = TRACE[step];

  return (
    <div className="mx-auto w-full max-w-3xl space-y-6 rounded-xl border border-stone-200 bg-white p-6">
      <div className="space-y-2">
        <h3 className="text-lg font-semibold text-stone-900">What is this?</h3>
        <p className="text-sm leading-relaxed text-stone-700">
          An <strong>LR parser</strong> parses bottom-up: instead of predicting what to expand next,
          it <strong>shifts</strong> input tokens onto a stack until it recognizes a complete
          right-hand side of a production, then <strong>reduces</strong> that sequence back down to
          the corresponding nonterminal. Which action to take at each step is looked up in a table
          built from the grammar — no guessing, no backtracking, just a table lookup based on the
          current state and the next input token.
        </p>
        <div className="rounded-lg border border-stone-200 p-4">
          <p className="mb-2 text-sm font-semibold text-stone-900">Key terms</p>
          <dl className="space-y-1.5 text-sm">
            <div>
              <dt className="inline font-medium text-stone-900">Shift: </dt>
              <dd className="inline text-stone-600">
                push the next input token onto the stack and move to a new parser state.
              </dd>
            </div>
            <div>
              <dt className="inline font-medium text-stone-900">Reduce: </dt>
              <dd className="inline text-stone-600">
                recognize a complete production's right-hand side on top of the stack and replace it
                with the left-hand nonterminal.
              </dd>
            </div>
            <div>
              <dt className="inline font-medium text-stone-900">ACTION / GOTO table: </dt>
              <dd className="inline text-stone-600">
                precomputed tables telling the parser exactly whether to shift, reduce, or accept at
                each (state, token) pair.
              </dd>
            </div>
          </dl>
        </div>
        <CommonMistake>
          expecting the parser to reduce as soon as something on the stack <em>could</em> match a
          production's right-hand side. Watch state 9 with lookahead "*" in the trace below — the
          stack holds "T", which could reduce via E → T, but the table instead says shift. The table
          encodes exactly this kind of precedence decision (finish the multiplication first) — it's
          not "reduce whenever possible."
        </CommonMistake>
      </div>

      <div className="space-y-1 rounded-lg bg-stone-50 p-4 text-sm text-stone-700">
        <p className="font-semibold text-stone-900">How to use this</p>
        <ol className="list-inside list-decimal space-y-0.5">
          <li>Grammar: E → E + T | T; T → T * F | F; F → ( E ) | id.</li>
          <li>Click "Step" to trace parsing "id + id * id" using the ACTION/GOTO table below.</li>
          <li>
            Notice the stack grows with each shift, then shrinks and gets replaced on each reduce.
          </li>
        </ol>
      </div>

      <details className="text-xs">
        <summary className="cursor-pointer text-stone-500">Show ACTION / GOTO table</summary>
        <div className="mt-2 overflow-x-auto">
          <table className="font-mono">
            <thead>
              <tr className="text-stone-400">
                <th className="pr-2 text-left">state</th>
                {['id', '+', '*', '(', ')', '$'].map((t) => (
                  <th key={t} className="pr-2 text-left">
                    {t}
                  </th>
                ))}
                {['E', 'T', 'F'].map((nt) => (
                  <th key={nt} className="pr-2 text-left">
                    {nt}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {Object.keys(ACTION).map((s) => (
                <tr key={s}>
                  <td className="pr-2">{s}</td>
                  {['id', '+', '*', '(', ')', '$'].map((t) => (
                    <td key={t} className="pr-2">
                      {ACTION[Number(s)][t] ?? ''}
                    </td>
                  ))}
                  {['E', 'T', 'F'].map((nt) => (
                    <td key={nt} className="pr-2">
                      {GOTO[Number(s)]?.[nt] ?? ''}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </details>

      <div className="flex flex-wrap items-center gap-2">
        <button
          onClick={next}
          disabled={step >= TRACE.length - 1}
          className="rounded-md bg-stone-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-40"
        >
          Step
        </button>
        <button
          onClick={reset}
          className="rounded-md border border-stone-300 px-4 py-2 text-sm font-medium text-stone-700"
        >
          Reset
        </button>
        <span className="text-sm text-stone-500">Input: {INPUT_TOKENS.join(' ')} $</span>
      </div>

      <div className="space-y-1 rounded-md border border-stone-200 p-4">
        <p className="text-xs uppercase tracking-wide text-stone-400">
          Current state &amp; symbol stack
        </p>
        <p className="font-mono text-sm">
          state {current.state} | {current.symStack || '(empty)'}{' '}
          <span className="font-semibold text-violet-600">| lookahead: {current.lookahead}</span>
        </p>
        <p
          className={`mt-1 text-sm font-medium ${current.action === 'ACCEPT' ? 'text-emerald-600' : current.action.startsWith('ERROR') ? 'text-rose-600' : 'text-stone-700'}`}
        >
          {current.action}
        </p>
      </div>
    </div>
  );
}

function CommonMistake({ children }: { children: ReactNode }) {
  return (
    <div className="flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">
      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" />
      <p>
        <span className="font-semibold">Common mistake: </span>
        {children}
      </p>
    </div>
  );
}
